### ISSUE TITLE
Write a python script to record video stream from mobile camera

### ISSUE THREAD

**Issue by KShivendu** [OpenLake/Smart-Cams#5]
Since we're going to record CCTV footages, we want to have a data source. There are many public CCTV cameras online but for ease of testing and control we can start with our mobile phones. For this you need to find a way to record data directly from your mobile camera (maybe using the local network)

So write a python script that can take data from your mobile camera and store it in files.

**Comment by sky-2002** [comment]
Please assign me this task.

**Comment by KShivendu** [comment]
Done. I hope you'll learn a lot :)
